development:
  adapter: postgresql
  encoding: utf8
  database: clone_discord_development
  pool: 80
  template: template0

test:
  adapter: postgresql
  encoding: utf8
  database: clone_discord_test
  pool: 80
  template: template0
